name: Update Database

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger from the Actions UI
  # schedule:
  #   - cron: "0 0 1 * *"

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make changes to a file
      - name: Modify db.txt
        run: |
          echo "Manually updated on $(date)" > manual-update.txt

      # Step 3: Commit and push changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Manual update: $(date)"
          git push origin main
