name: Update Database

on:
  workflow_dispatch: # Run the action manually
  schedule:
    - cron: "0 0 1,15 * *"
#   push:
#     branches:
#       - main

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install poppler-utils (pdftotext)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Modify db.txt file
        run: |
          ./42pdf -u

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! -z "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Manual update: $(date)"
            git push origin main
          else
            echo Nothing to commit
          fi
